[package]
name = "nerdee_engine"
version = "0.1.0"
authors = ["nerdee"]

[dependencies]
read_input = "0.8.2"
cgmath = "0.17"
winit = "0.19.3"
vulkano = "0.14"
vulkano-shaders = "0.14"
vulkano-win = "0.14"
